In [1]:
import pandas as pd
import numpy as np
data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]
df = pd.DataFrame(data,columns = ["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}
df = pd.DataFrame(data,columns = ["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [3]:
arr = np.array([[1,2],[5,6]])
df = pd.DataFrame(arr,columns = ["A","B"])
print(df)

   A  B
0  1  2
1  5  6

In [5]:
df = pd.read_csv( r"C:\Users\aatif\Downloads\Simple 100 Student Marks.csv",)
print(df)

            student_name  maths_marks  science_marks  english_marks  \
0   Mr. Gregory Homenick           69             24             52
1     Marlene Leffler IV           62             59             70
2        Josephine Ebert           29             76             13
3        Dr. Irene Green           44             66             14
4              Jake Huel           49             23             63
..                   ...          ...            ...            ...
95        Renee Schinner           69             99             73
96      Marguerite Ebert           32             62             82
97          Jorge Bednar           77             56             46
98   Mrs. Roxanne Jacobi           54             66             70
99       Dean Schowalter           28             49             78

    social_studies_marks  language_marks
0                      4              83
1                     54              52
2                      8              19
3                      2              14
4                     86              68
..                   ...             ...
95                    62              32
96                    99              42
97                    79              25
98                    49              20
99                    80              79

[100 rows x 6 columns]

In [6]:
df = pd.read_excel(r"C:\Users\aatif\Downloads\15. all marks-B-Tech-4950-Jan2026-Subrata (2).xlsx")
print(df)

   Unnamed: 0                       Unnamed: 1        Unnamed: 2 Unnamed: 3  \
0         NaN                              NaN               NaN        NaN
1         NaN                          2025-26          Semester          I
2         NaN                     B.Tech (CSE)           Session    Aug-Dec
3         NaN  Physics for Computer Enigineers               NaN        NaN
4         NaN                         PHYS1036               NaN        NaN
..        ...                              ...               ...        ...
59        NaN                        590025670     Anchit  Goyal        NaN
60        NaN                        590025915      Suhani  Goel        NaN
61        NaN                        590026603     Saurya  yadav        NaN
62        NaN                        590026653   Pranavi  Sengar        NaN
63        NaN                        590027493  Nitin dhar dubey        NaN

   Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  ...  \
0         NaN        NaN        NaN        NaN        NaN        NaN  ...
1         NaN        NaN        NaN        NaN        NaN        NaN  ...
2         NaN        NaN        NaN        NaN        NaN        NaN  ...
3         NaN        NaN        NaN        NaN        NaN        NaN  ...
4         NaN        NaN        NaN        NaN        NaN        NaN  ...
..        ...        ...        ...        ...        ...        ...  ...
59        NaN        NaN        NaN        NaN        NaN        NaN  ...
60        NaN        NaN        NaN        NaN        NaN        NaN  ...
61        NaN        NaN        NaN        NaN        NaN        NaN  ...
62        NaN        NaN        NaN        NaN        NaN        NaN  ...
63        NaN        NaN        NaN        NaN        NaN        NaN  ...

   Unnamed: 105 Unnamed: 106 Unnamed: 107 Unnamed: 108 Unnamed: 109  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
..          ...          ...          ...          ...          ...
59          NaN          NaN          NaN          NaN          NaN
60          NaN          NaN          NaN          NaN          NaN
61          NaN          NaN          NaN          NaN          NaN
62          NaN          NaN          NaN          NaN          NaN
63          NaN          NaN          NaN          NaN          NaN

   Unnamed: 110 Unnamed: 111 Unnamed: 112 Unnamed: 113 Unnamed: 114
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
..          ...          ...          ...          ...          ...
59          NaN          NaN          NaN          NaN          NaN
60          NaN          NaN          NaN          NaN          NaN
61          NaN          NaN          NaN          NaN          NaN
62          NaN          NaN          NaN          NaN          NaN
63          NaN          NaN          NaN          NaN          NaN

[64 rows x 115 columns]

In [7]:
df = pd.read_json(r"student_file.json")
print(df)

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [8]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [10]:
df.info

<bound method DataFrame.info of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

In [11]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [12]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [13]:
df.shape

(244, 7)