In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\aatif\OneDrive\Desktop\Aatif\Bollywood_Filmstars.csv")

In [3]:
df

,Actor,Movie,Year,Genre,Box Office (INR Crores),IMDb Rating
0,Shah Rukh Khan,Jawan,2023,Action,1148,7.0
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama,969,8.1
2,Aamir Khan,Dangal,2016,Sports Drama,2024,8.3
3,Ranbir Kapoor,Animal,2023,Action Crime,917,6.2
4,Ranveer Singh,Padmaavat,2018,Historical Drama,585,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Akshay Kumar,Sooryavanshi,2021,Action,294,6.0
7,Ajay Devgn,Drishyam 2,2022,Thriller,345,8.2
8,Deepika Padukone,Chhapaak,2020,Drama,55,5.4
9,Alia Bhatt,Gangubai Kathiawadi,2022,Biography,209,7.8
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.7
11,Vicky Kaushal,Uri: The Surgical Strike,2019,War,342,8.2
12,Rajkummar Rao,Stree 2,2024,Horror Comedy,874,7.2
13,Kareena Kapoor,Crew,2024,Comedy,157,6.4
14,Kiara Advani,Shershaah,2021,War Drama,70,8.3

In [4]:
df = df[df['IMDb Rating'] > 6.0]

In [5]:
df

,Actor,Movie,Year,Genre,Box Office (INR Crores),IMDb Rating
0,Shah Rukh Khan,Jawan,2023,Action,1148,7.0
1,Salman Khan,Bajrangi Bhaijaan,2015,Drama,969,8.1
2,Aamir Khan,Dangal,2016,Sports Drama,2024,8.3
3,Ranbir Kapoor,Animal,2023,Action Crime,917,6.2
4,Ranveer Singh,Padmaavat,2018,Historical Drama,585,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
7,Ajay Devgn,Drishyam 2,2022,Thriller,345,8.2
9,Alia Bhatt,Gangubai Kathiawadi,2022,Biography,209,7.8
11,Vicky Kaushal,Uri: The Surgical Strike,2019,War,342,8.2
12,Rajkummar Rao,Stree 2,2024,Horror Comedy,874,7.2
13,Kareena Kapoor,Crew,2024,Comedy,157,6.4
14,Kiara Advani,Shershaah,2021,War Drama,70,8.3

In [6]:
df = pd.read_json("student_file.json")

In [7]:
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     14 non-null     str
 1   gender   14 non-null     str
 2   physics  14 non-null     int64
 3   maths    14 non-null     int64
 4   english  14 non-null     int64
dtypes: int64(3), str(2)
memory usage: 692.0 bytes

In [10]:
data = [
  {
    "name": "arun",
    "gender": "Male",
    "physics": 88,
    "maths": 87,
    "english": 78
  },
  {
    "name": "rajesh",
    "gender": "Male",
    "physics": 96,
    "maths": 100,
    "english": 95
  },
  {
    "name": "moorthy",
    "gender": "Male",
    "physics": 89,
    "maths": 90,
    "english": 70
  },
  {
    "name": "raja",
    "gender": "Male",
    "physics": 30,
    "maths": 25,
    "english": 40
  },
  {
    "name": "usha",
    "gender": "Female",
    "physics": 67,
    "maths": 45,
    "english": 78
  },
  {
    "name": "priya",
    "gender": "Female",
    "physics": 56,
    "maths": 46,
    "english": 78
  },
  {
    "name": "Sundar",
    "gender": "Male",
    "physics": 12,
    "maths": 67,
    "english": 67
  },
  {
    "name": "Kavitha",
    "gender": "Female",
    "physics": 78,
    "maths": 71,
    "english": 67
  },
  {
    "name": "Dinesh",
    "gender": "Male",
    "physics": 56,
    "maths": 45,
    "english": 67
  },
  {
    "name": "Hema",
    "gender": "Female",
    "physics": 71,
    "maths": 90,
    "english": 23
  },
  {
    "name": "Gowri",
    "gender": "Female",
    "physics": 100,
    "maths": 100,
    "english": 100
  },
  {
    "name": "Ram",
    "gender": "Male",
    "physics": 78,
    "maths": 55,
    "english": 47
  },
  {
    "name": "Murugan",
    "gender": "Male",
    "physics": 34,
    "maths": 89,
    "english": 78
  },
  {
    "name": "Jenifer",
    "gender": "Female",
    "physics": 67,
    "maths": 88,
    "english": 90
  }
]
df = pd.json_normalize(data)

In [11]:
df

       name  gender  physics  maths  english
0      arun    Male       88     87       78
1    rajesh    Male       96    100       95
2   moorthy    Male       89     90       70
3      raja    Male       30     25       40
4      usha  Female       67     45       78
5     priya  Female       56     46       78
6    Sundar    Male       12     67       67
7   Kavitha  Female       78     71       67
8    Dinesh    Male       56     45       67
9      Hema  Female       71     90       23
10    Gowri  Female      100    100      100
11      Ram    Male       78     55       47
12  Murugan    Male       34     89       78
13  Jenifer  Female       67     88       90